### ISSUE TITLE
nogui is not working

### ISSUE THREAD

**Issue by Z-Diva** [encode42/flags.sh#32]
im running an RLCraft server with java 8 but the follow launch option seems to have issues with nogui because the gui always shows up `java -Xms8192M -Xmx8192M -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1 -Dusing.aikars.flags=https://mcflags.emc.gs -Daikars.new.flags=true -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -jar forge.jar --nogui`

**Comment by Z-Diva** [comment]
i m also getting 
`
#this error

ready - started server on 0.0.0.0:3000, url: http://localhost:3000
info  - Using webpack 5. Reason: Enabled by default https://nextjs.org/docs/messages/webpack5
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:79:19)
    at Object.createHash (node:crypto:139:10)
    at BulkUpdateDecorator.hashFactory (/home/diva/Downloads/flags.sh-main/node_modules/next/dist/compiled/webpack/bundle5.js:133896:18)
    at BulkUpdateDecorator.update (/home/diva/Downloads/flags.sh-main/node_modules/next/dist/compiled/webpack/bundle5.js:133797:50)
    at OriginalSource.updateHash (/home/diva/Downloads/flags.sh-main/node_modules/next/dist/compiled/webpack-sources3/index.js:1:10264)
    at NormalModule._initBuildHash (/home/diva/Downloads/flags.sh-main/node_modules/next/dist/compiled/webpack/bundle5.js:63424:17)
    at handleParseResult (/home/diva/Downloads/flags.sh-main/node_modules/next/dist/compiled/webpack/bundle5.js:63490:10)
    at /home/diva/Downloads/flags.sh-main/node_modules/next/dist/compiled/webpack/bundle5.js:63584:4
    at processResult (/home/diva/Downloads/flags.sh-main/node_modules/next/dist/compiled/webpack/bundle5.js:63299:11)
    at /home/diva/Downloads/flags.sh-main/node_modules/next/dist/compiled/webpack/bundle5.js:63363:5
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:79:19)
    at Object.createHash (node:crypto:139:10)
    at BulkUpdateDecorator.hashFactory (/home/diva/Downloads/flags.sh-main/node_modules/next/dist/compiled/webpack/bundle5.js:133896:18)
    at BulkUpdateDecorator.update (/home/diva/Downloads/flags.sh-main/node_modules/next/dist/compiled/webpack/bundle5.js:133797:50)
    at OriginalSource.updateHash (/home/diva/Downloads/flags.sh-main/node_modules/next/dist/compiled/webpack-sources3/index.js:1:10264)
    at NormalModule._initBuildHash (/home/diva/Downloads/flags.sh-main/node_modules/next/dist/compiled/webpack/bundle5.js:63424:17)
    at handleParseResult (/home/diva/Downloads/flags.sh-main/node_modules/next/dist/compiled/webpack/bundle5.js:63490:10)
    at /home/diva/Downloads/flags.sh-main/node_modules/next/dist/compiled/webpack/bundle5.js:63584:4
    at processResult (/home/diva/Downloads/flags.sh-main/node_modules/next/dist/compiled/webpack/bundle5.js:63299:11)
    at /home/diva/Downloads/flags.sh-main/node_modules/next/dist/compiled/webpack/bundle5.js:63363:5
node:internal/crypto/hash:79
  this[kHandle] = new _Hash(algorithm, xofLen, algorithmId, getHashCache());
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:79:19)
    at Object.createHash (node:crypto:139:10)
    at BulkUpdateDecorator.hashFactory (/home/diva/Downloads/flags.sh-main/node_modules/next/dist/compiled/webpack/bundle5.js:133896:18)
    at BulkUpdateDecorator.update (/home/diva/Downloads/flags.sh-main/node_modules/next/dist/compiled/webpack/bundle5.js:133797:50)
    at OriginalSource.updateHash (/home/diva/Downloads/flags.sh-main/node_modules/next/dist/compiled/webpack-sources3/index.js:1:10264)
    at NormalModule._initBuildHash (/home/diva/Downloads/flags.sh-main/node_modules/next/dist/compiled/webpack/bundle5.js:63424:17)
    at handleParseResult (/home/diva/Downloads/flags.sh-main/node_modules/next/dist/compiled/webpack/bundle5.js:63490:10)
    at /home/diva/Downloads/flags.sh-main/node_modules/next/dist/compiled/webpack/bundle5.js:63584:4
    at processResult (/home/diva/Downloads/flags.sh-main/node_modules/next/dist/compiled/webpack/bundle5.js:63299:11)
    at /home/diva/Downloads/flags.sh-main/node_modules/next/dist/compiled/webpack/bundle5.js:63363:5 {
  opensslErrorStack: [
    'error:03000086:digital envelope routines::initialization error',
    'error:0308010C:digital envelope routines::unsupported'
  ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v20.17.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
`

**Comment by encode42** [comment]
This website is not designed for forge servers yet. It's planned for a future revision, but as of now, support will not be provided. (mainly because I don't know the forge ecosystem enough!)

The second error you're experiencing is due to the source code's old age. It's not recommended to run it yourself, or contribute to it. It is extremely due for a complete rewrite.

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
